### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by rayman89** [Silbad/DeepLT#1]
Thanks for making the addon.  It showed me how good it's as a translator. BTW do you know a way to contact them? It would be great if they could add japanese to the list of languages.

**Comment by Silbad** [comment]
Hello, sorry I have no contact with them...
There is no communication and documentation for the moment :(

**Comment by ghost** [comment]
They are in Cologne, Germany:
DeepL GmbH
Im Mediapark 8a
50670 Köln

For email they list info at deepl.com. Their founder is listed on LinkedIn, if you prefer that route...
