### ISSUE TITLE
[RFE] Replace target language menu with buttons

### ISSUE THREAD

**Issue by Mozinet-fr** [Silbad/DeepLT#10]
As long as DeepL have a very low number of languages, the target language menu could be replaces with a button for each language. Otherwise you could add two buttons for the most used languages (or favorite ones). We almost always use the same languages.

**Comment by SuperPat45** [comment]
You can rather than add option to select favorites languages (for me french and english), and show favorite languages as buttons and add an arrow button to select others like google trad:
![buttons](https://user-images.githubusercontent.com/7791600/43066633-77d72e68-8e65-11e8-9d48-f8998c2b61c4.png)

**Comment by Silbad** [comment]
Hello, for the moment I leave it as it is, being limited by the design.
