### ISSUE TITLE
Translate selection with DeepL

### ISSUE THREAD

**Issue by SuperPat45** [Silbad/DeepLT#12]
Hi,

Until now I use the "Open in Google™ Translate" extension:
https://mybrowseraddon.com/open-in-gtranslate.html
It allows: Select text / Right click / Open Selection in Google Translate

Could we have this feature in DeepLT or maybe a "Translate selection" context menu ?

**Comment by adocampo** [comment]
In y way to leave google services as much as I can, I find this cool tool for the great DeepL translation engine.So thanks for developing it.
By the way, I think the users experience can be improved by doing some little changes. At least the two first that follows.
 - Let the user select default destination translation language: right now is always French, which is very annoying to having to change the language in each and every translation.
 - Context menu to translate selected text **inline** into default destination translation language
 - Context menu to translate selected text (it will popup addon mini-window and you can change there the destination translation language if you want)
 - Context menu to translate selected text into system notifications popups (like Deep Translator addon does, so you can even quickly translate some word or expression when you're typing on a textarea in a foreign language like I'm doing right now)

**Comment by SuperPat45** [comment]
It would be great

**Comment by woj-tek** [comment]
I'm in the same boat but I'm using https://add0n.com/google-translator.html - it has very handy feature of baloon-tip on select with translated fragment.

**Comment by Silbad** [comment]
Done on 2.0.0 version
