### ISSUE TITLE
automatically translate selected text

### ISSUE THREAD

**Issue by yeupou** [Silbad/DeepLT#2]
It would be cool if , like S3 translator, there was the possibility that each time we select a block of text, it get translated.

**Comment by Silbad** [comment]
Yeah, it's planned in a future release. I just have to find the time to take care of it ^^

**Comment by sky4055** [comment]
@Silbad , have you implemented the functionality, because version 1.41 asks me for some rights on the clipboard?

**Comment by Silbad** [comment]
@sky4055 , It's being implemented.
The application has problems recovering data. This version informs about this.
I'm working on it.

**Comment by ghost** [comment]
@Silbad I appreciate your work. 
Have you made any progress in solving the issue?

**Comment by Silbad** [comment]
Done on 2.0.0 version
