### ISSUE TITLE
Automaticlly translation after change input-/output-language

### ISSUE THREAD

**Issue by Somebodyisnobody** [Silbad/DeepLT#7]
It was nice if DeepLP would translate automaticlly the entered text if i change the input- or output-language.
At the moment i need to delete the last character and rewrite it.

**Comment by Silbad** [comment]
I will improve performance in the next release (1.5.0)

**Comment by Silbad** [comment]
With the new version, this is no longer an issue as you need to click on the button to translate. I had to do this to limit consumption on the API, especially for free accounts.
