### ISSUE TITLE
After a while it stops working

### ISSUE THREAD

**Issue by Yishaqel** [Silbad/DeepLT#8]
Today I have updated this plugin and after a while it stops working. When restarting Firefox runs again, it reoccurs after a period of time. It simply does not translate, it shows nothing in the translated text. 

Two suggestions:
1) Auto-copying the translated text would be very useful.
2) Being able to install the plugin in Chrome.

Thank you, 
Isaac.

**Comment by Yishaqel** [comment]
This project is abandoned? I haven't had an answer to my problem in two weeks.

**Comment by Somebodyisnobody** [comment]
No the project is still active but the developer isn't very active. A log taken with the developer tools was nice if you can do that.

Edit: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Debugging

**Comment by Yishaqel** [comment]
https://my.mixtape.moe/skjfab.png

**Comment by Somebodyisnobody** [comment]
Ok to sum up:
-An invalid function (originDate.getTime)
-Two network error when trying to get a local url
-A wrong XML-input from "https://cors-anywhere.herokuapp.com/https://deepl.com/jsonrpc"

I think the last causes your Problem. "https://deepl.com/jsonrpc" is the API for deepl. If a wrong XML comes back (or a right but wrong interpreted) deeplt stops.
Found the URL-request function here:
https://github.com/Silbad/DeepLT/blob/50bf78ee6a99f020cbc77b098343420ed5fc32db/app/popup.js#L159-L180

**Comment by Yishaqel** [comment]
Is there an easy way to fix this?

**Comment by Somebodyisnobody** [comment]
The API that i called is acc. to Mr. G.'s results not an officially API. I didn't code that and never used this API directly so @Silbad could maybe solve this more efficient than me. 😉

**Comment by Silbad** [comment]
It's fixed. Sorry time is precious.
